from web3 import Web3
import hashlib
import time
import json

# ── Connect to Ganache ─────────────────────────────────────────────────────────

w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))

if not w3.is_connected():
    raise ConnectionError("Cannot connect to Ganache. Make sure it is running on port 7545.")

print(f"Connected to Ganache | Chain ID: {w3.eth.chain_id} | Account: {w3.eth.accounts[0]}")

# ── Load Contract Config (auto-generated by deploy_contract.py) ────────────────

try:
    with open("contract_config.json", "r") as f:
        config = json.load(f)
except FileNotFoundError:
    raise FileNotFoundError(
        "contract_config.json not found. Run deploy_contract.py first."
    )

contract = w3.eth.contract(
    address=config["contract_address"],
    abi=config["abi"]
)

account = w3.eth.accounts[0]
LOG_FILE = "blockchain.log"

# ── Verify Contract Exists on Chain ───────────────────────────────────────────

code = w3.eth.get_code(config["contract_address"])
if code == b'' or code == b'\x00':
    raise RuntimeError(
        f"No contract found at {config['contract_address']}. "
        "Ganache may have restarted. Run deploy_contract.py again."
    )

print(f"Contract verified at: {config['contract_address']}")

# ── Core Functions ─────────────────────────────────────────────────────────────

def hash_log(log: str) -> str:
    """Compute SHA-256 hash of a log entry."""
    return hashlib.sha256(log.encode()).hexdigest()


def write_log(message: str):
    """
    Write a log entry to local file and store its SHA-256 hash on-chain.

    Returns:
        latency (float): Total time for local write + blockchain transaction (seconds)
        gas_used (int): Gas consumed by the storeHash transaction
    """
    start = time.time()

    # Build log entry with timestamp
    log_entry = f"{time.time()} - {message}"

    # Store log locally
    with open(LOG_FILE, "a") as f:
        f.write(log_entry + "\n")

    # Compute SHA-256 hash
    log_hash = hash_log(log_entry)

    # Send hash to blockchain
    tx = contract.functions.storeHash(log_hash).transact({'from': account})
    receipt = w3.eth.wait_for_transaction_receipt(tx)

    end = time.time()

    return end - start, receipt.gasUsed


def verify_log(index: int):
    """
    Verify integrity of a log entry at given index.

    Process:
        1. Read local log entry at index
        2. Recompute SHA-256 hash
        3. Fetch on-chain hash via getHash(index)
        4. Compare both hashes

    Returns:
        match (bool): True if hashes match (log is intact), False if tampered
        verification_time (float): Time taken for the full verification (seconds)
    """
    start = time.time()

    with open(LOG_FILE, "r") as f:
        logs = f.readlines()

    log = logs[index].strip()
    local_hash = hash_log(log)

    chain_hash = contract.functions.getHash(index).call()

    end = time.time()

    return (local_hash == chain_hash), (end - start)


def tamper_log(index: int):
    """
    Simulate insider tampering: overwrite a log entry at given index.
    Used in the tampering experiment to demonstrate detection capability.
    """
    with open(LOG_FILE, "r") as f:
        logs = f.readlines()

    original = logs[index].strip()
    logs[index] = "TAMPERED ENTRY - insider modification\n"

    with open(LOG_FILE, "w") as f:
        f.writelines(logs)

    print(f"[TAMPER] Index {index} overwritten.")
    print(f"  Original : {original}")
    print(f"  Tampered : TAMPERED ENTRY - insider modification")


def clear_logs():
    """
    Clear local blockchain.log file.
    NOTE: On-chain hashes are NOT cleared (blockchain is immutable).
    Redeploy contract via deploy_contract.py for a completely fresh state.
    """
    open(LOG_FILE, "w").close()
    print("blockchain.log cleared.")
    print("NOTE: On-chain hashes persist. Run deploy_contract.py to reset chain state.")


def get_chain_count() -> int:
    """Return number of hashes currently stored on-chain."""
    return contract.functions.getCount().call()